-- Generated by scripts/export-deck-sql.mjs from lib/seed.ts — deck "knowledge".
-- Idempotent via fixed UUID and ON CONFLICT DO NOTHING.

begin;

insert into cisco.cisco_decks (id, slug, title, sermon_id, metadata)
values ('c1000000-0000-4000-8000-000000000005', 'knowledge', 'Knowledge', null, '{"backgrounds":{}}'::jsonb)
on conflict (slug) do nothing;

insert into cisco.cisco_slides (deck_id, position, html, outline_html, bg, notes)
values
  ('c1000000-0000-4000-8000-000000000005', 1, '<img class="slide-image" src="/sermons/knowledge/slides/01.jpg" alt="Knowledge Begins with Simple Truths — Hebrews 6:1">', '<p><strong>Knowledge Begins with Simple Truths</strong></p><p>Hebrews 6:1</p>', null, 'Title. Let it hold through the introduction.'),
  ('c1000000-0000-4000-8000-000000000005', 2, '<img class="slide-image" src="/sermons/knowledge/slides/02.jpg" alt="Knowledge Deepens Through Experience — James 1:2-4, I Corinthians 2:9-10">', '<p><strong>Knowledge Deepens Through Experience</strong></p><p>James 1:2&ndash;4</p><p>I Corinthians 2:9&ndash;10</p>', null, 'Read both passages before advancing.'),
  ('c1000000-0000-4000-8000-000000000005', 3, '<img class="slide-image" src="/sermons/knowledge/slides/03.jpg" alt="Wisdom Keys For Bible Knowledge — Lesson 1: Knowledge Is Timeless. Lesson 2: Knowledge Is Transferrable.">', '<p><strong>Wisdom Keys For Bible Knowledge</strong></p><p><strong>Lesson 1 — Knowledge Is Timeless.</strong> Everything we learn is foundational. It has tremendous value for today. However, if we build on it, its value for the future is priceless. Bible knowledge is not static by design; what God teaches us is meant to keep unfolding.</p><p><strong>Lesson 2 — Knowledge Is Transferrable.</strong> Jesus taught us truths that invariably carry countless principles. While Jesus'' teachings may each focus on a specific point, the wisdom in His teachings have many applications.</p>', null, 'Two lessons on one slide — take them one at a time.'),
  ('c1000000-0000-4000-8000-000000000005', 4, '<img class="slide-image" src="/sermons/knowledge/slides/04.jpg" alt="Bible Truths Do Not Stand Alone">', '<p><strong>Bible Truths Do Not Stand Alone</strong></p><p>&middot; It''s not about being right.</p><p>&middot; Bible knowledge is intended to be broad in application.</p><p>&middot; If you miss the principle, then you''ll miss the truth.</p>', null, null),
  ('c1000000-0000-4000-8000-000000000005', 5, '<img class="slide-image" src="/sermons/knowledge/slides/05.jpg" alt="Five tips for knowledge and principles.">', '<p><strong>Five tips for knowledge and principles.</strong></p><p>1. Bible knowledge is not meant to stay private.</p><p>2. Principles outlast specific situations.</p><p>3. Application multiplies understanding.</p><p>4. Strength comes through shared knowledge.</p><p>5. Knowledge always points to the Greater Teacher.</p>', null, 'Five tips — this slide holds through all of them.'),
  ('c1000000-0000-4000-8000-000000000005', 6, '<img class="slide-image" src="/sermons/knowledge/slides/06.jpg" alt="Learning where and how to apply principles is the key to peace.">', '<p><strong>Learning where and how to apply principles is the key to peace.</strong></p>', null, null),
  ('c1000000-0000-4000-8000-000000000005', 7, '<img class="slide-image" src="/sermons/knowledge/slides/07.jpg" alt="Learning Principles Is Like Learning A Thousand Lessons">', '<p><strong>Learning Principles Is Like Learning A Thousand Lessons</strong></p>', null, null),
  ('c1000000-0000-4000-8000-000000000005', 8, '<img class="slide-image" src="/sermons/knowledge/slides/08.jpg" alt="Reflections">', '<p><strong>Reflections:</strong></p><p>&middot; What God teaches you is not just for you.</p><p>&middot; Principles are stronger than particulars.</p><p>&middot; Shared knowledge multiplies its impact.</p><p>&middot; Christ is the ultimate model for transferrable knowledge.</p>', null, 'Closing reflections. Leave it up through the invitation.')
on conflict (deck_id, position) do nothing;

insert into cisco.cisco_deck_state (deck_id, current_slide, is_live, is_blank)
values ('c1000000-0000-4000-8000-000000000005', 1, false, false)
on conflict (deck_id) do nothing;

commit;
